### PR TITLE
Increased maximum pin length to 32

### PR DESCRIPTION
**Pull request by betsythefc**
Tested working on Nexus 5 (VM) with API 24

### CODE REVIEW

**Comment by Yonjuni** [comment]
@betsythefc Thanks for the PR, I will have a look at it after Christmas :)

**Comment by Yonjuni** [comment]
@betsythefc Could you remove the .idea/runConfigurations.xml from the PR. (You can keep it locally by `git rm --cache`) Thanks!

**Comment by betsythefc** [comment]
I just removed it, let me know if there is anything else I can do :+1:

**Comment by Yonjuni** [comment]
Looks okay to me.

**Pull request merged**
